name: Release Builds

on:
  push:
    tags: ['*']

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: schnapsshot-windows-x64.exe
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: schnapsshot-linux-x64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: schnapsshot-macos-intel
          - target: aarch64-apple-darwin
            os: macos-latest
            name: schnapsshot-macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/schnapsshot${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifacts to top-level
        run: |
          shopt -s nullglob
          for dir in artifacts/*; do
            if [ -d "$dir" ]; then
              for f in "$dir"/*; do
                mv -n "$f" "artifacts/$(basename "$dir")"
              done
            fi
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}