name: Release Builds

on:
  push:
    tags: ['*']

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: schnapsshot-windows-x64.exe
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: schnapsshot-linux-x64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: schnapsshot-macos-intel
          - target: aarch64-apple-darwin
            os: macos-latest
            name: schnapsshot-macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/schnapsshot${{ matrix.os == 'windows-latest' && '.exe' || '' }}